travis:
  secure:
    BINSTAR_TOKEN: vAi+zOUuztQLJu9wBLZjfRL4cIx3yqDPwi45qUVYGcY+B+D11ciMzdob1Q4u8VBD6Vq60GhRgHsTW9h6UCuXNMUJEbIqcQkhV8MK4RuQejHz0w15RisG+71EJp5u89Tz7hofftvd558uGR13RGi9s+ZrxTQNW345XnlCH1/sgTdqdhvUQYwmAkyCcwHzwBBESxviaJ1eNIAtDmuSJnnqgY05F9cZ/a8T76wLQvHMpg35vVwDume6B0gFmlAwhQ8JGuuZoqJjHhw/JPS6IoX8WnRlgc6PtC35ouPMyFVrHSEIw1bjKVTMKAt3LGGS9EYjX8sPRdk0jr+WNPDaK2JRHM+ck4KArC8C43zq8f0x0r/SCxca16vq863vC2svhrXnbHRY8vL7VlOe/q8hoYT+lKuC3/YVaUXK7ELWsxRl0WOZOvb5bCQ5QcVTI4DuFXLLvVRK8ElqQMV4DgPzw4eiE9IPtG9/DaUg5uNhJR1FIoMFXnRyp82rZmQJflgFwBKZfGAXif8qhDS3+CGIf/6YElARHOIRCK4oHfUE8bLV78xKoL36Di4sQFG4iO7+jnzqLLwPsCcPm8FWwxovZQ0uMe7gnnzUt4lfIIcDbQ38NC0j+qUd1S96ai3ivHjawsw0uW7b4XFEKCtaS8h7MPfF/iATapMZ7OZOdbhGl49WmBY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
