travis:
  secure:
    BINSTAR_TOKEN: tATVkFYsV6knB8UXQGe6ys1j3vi/aSNt72Y9hmkXkE91+myMEOnZjHcN1finp5rMJ91zyRxGw/HLT4GlthnnnIq8Df8wqPylgbisN3xkLKAPrjGf6ZXBczKaLEpykE7Du8mHWw1yruOloZbZ+ITlQR0WQNvOXF654L5T4khrlq8xuGSb0pYhQbjWlMzuyD3L7qoZvFgSDnqff1spV26I69o7oDKkJtmyTRc8HeQG14ihZU38WizuyC4zEUqOc4ldnUi5nt/6AujSLSRMH6g+fTG5PtlP18DMdpbh29drbyeM6kBBzRbRyhRg0Ym9RQiXlMgqEzknC/jzCBDwI8yiI7HxEFwZrJvG3y57r4o4tkEkpTvZglpGALPQlkKjoW+iERyGlQ1PBWmo4KaLqNnSCXMTtrmy566AGV1yjShUrRZfQTveKejAcyeBgqFrndOHLnR9SwuTz6BE4P9Y6C3hpj70Sbtgtt0i27DG79axz4D7tKl/W283elxhU34ysg4JsLbttxsa9Y9q6UqyymscfGo2IWrziIHpQyqsxgIoK+jN88XunG9yBHjnligtEHif2gNQ8zqpzpCTkuUnSgrzG2265gWU7sgl6kkM2+e0N+tUZKLQX43ckddM/CyZtvSlQa/9z2Y+mmGpOSZcs9VW/OYX/aKAtaIXPEAl5yTw9qo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
