travis:
  secure:
    BINSTAR_TOKEN: ZvGtf0cOjv4Sn0fG2gjAgMiBhJq+2tmQTI57W1g2SHNer3M7Rgw169VKKZOxJ1Gb5H2l6dgTZ5z8phT0vaL+taxRzuvea8Onzlg3UtVdDRObxznwt3MWv29SWz5dNYQtQad/rIeoOfvYsfyKzG2Gokip5hjDEcN6HFnzXjFmWF5Wyh+bSOjkC8io885tUQQbSSYCKYU41bPfdd47tBh+FKDy8ukxhOjTOoZ/PiTZv61eGdXPxaNkeknL74DWp1MUxi1dnQZAe3VyUIfhlW8OE/zYiySwUVzbE5DME+rGYwVhMbi9c/yQuuY8SjvzwuSLMi1frGyjN+dIkGe1zl03NqzbejbeQ/Q9HH+oyrWpUVjaIXaPYwGqGEVHpfEX6uzqvO9Sa1m1A6HPbJjyk2WJRoe5KFULNJC1DdZRKhgz189BNdiUXsd4IcIc7ZHRelAkKLS5+To7L8dHHp138Ikdbw2+FFIsQ6+CMNU7+2g3McSsECjW0CCdQjOLrlDACCO3uG1lW0RKJ69AgY9uGRZIJ3+GKrsWcZeQKzpOqRPWRAZQ2PNMA/DFJmQ4MwP62pChXGzQR7/JuhTWwAZWMYKVUj2JCV2vrkHu9/2/fwuHuDdRFrezsMRa/E0iDlVaH9TCzZ8aPdbKE4FgXLoC+k1mm6bvMvoFytRgWoe0OyNMANM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
